### ISSUE TITLE
strange non-fatal exceptions thrown by google.appengine.api 

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/kubeface#13]
These get thrown in a separate thread. They do not seem to affect the results.

Possible fix: https://github.com/insanum/gcalcli/issues/237#issuecomment-189591494

Also related: https://github.com/google/oauth2client/issues/414

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/opt/conda/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0

**Comment by timodonnell** [comment]
Tried lowering the versions of google-api-python-client and oauth2client but hit a number of new issues involving unicode encoding and pickling, so for the time being leaving it as

```
        "oauth2client==4.0.0",
        "google-api-python-client==1.5.5",
```

**Comment by klday** [comment]
I'm getting these errors as well.

**Comment by jcrowgey** [comment]
I think we need to record the version of gcalcli and the verison of oauth2client in order to confirm bugs.
